from os import environ
from dotenv import load_dotenv
import os

load_dotenv()

API_POST_PRODUCT=os.getenv('API_POST_PRODUCT')
API_POST_CATEGORY=os.getenv('API_POST_CATEGORY')

API_GET_ALL_PRODUCTS=os.getenv('API_GET_ALL_PRODUCTS')
API_GET_ALL_CATEGORIES=os.getenv('API_GET_ALL_CATEGORIES')

API_GET_PRODUCT=os.getenv('API_GET_PRODUCT')
API_GET_CATEGORY=os.getenv('API_GET_CATEGORY')

API_DELETE_PRODUCT=os.getenv('API_DELETE_PRODUCT')
API_DELETE_CATEGORY=os.getenv('API_DELETE_CATEGORY')

API_PUT_PRODUCT=os.getenv('API_PUT_PRODUCT')
API_PUT_CATEGORY=os.getenv('API_PUT_CATEGORY')
SECRET_KEY = os.environ.get('SECRET_KEY')

# FIREBASE
API_KEY=os.getenv('API_KEY')
AUTH_DOMAIN=os.getenv('AUTH_DOMAIN')
DATABASE_URL=os.getenv('DATABASE_URL')
PROJECT_ID=os.getenv('PROJECT_ID')
STORAGE_BUCKET=os.getenv('STORAGE_BUCKET')
MESSAGING_SENDER_ID=os.getenv('MESSAGING_SENDER_ID')
APP_ID=os.getenv('APP_ID')
MEASUREMENT_ID=os.getenv('MEASUREMENT_ID')

# MERCADOPAGO
PROD_ACCESS_TOKEN=os.getenv('PROD_ACCESS_TOKEN')